Wyvern-AI/wyvern

wyvern/components/features/feature_retrieval_pipeline.py

remove unnecessary logs for realtime feature components

---

pyproject.toml
wyvern/components/models/modelbit_component.py
wyvern/entities/request.py
wyvern/wyvern_typing.py

1. The modelbit request schema we're enforcing will be the [single argument format](https://doc.modelbit.com/deployments/rest-api/batch-inference#request-format), where the single argument will be a list of feature values.
2. support boolean in our FeatureMap

Fix modelbit component and support boolean WyvernFeature

---

pyproject.toml
wyvern/wyvern_typing.py

Problem:
https://github.com/Wyvern-AI/wyvern/commit/e5bcec86bdaefa3c0b8193dd908b14fffd83eb48#diff-80050da03187eed3ae9ee8422eba71967790cb8719074399155bc3df7a7437beR23
with `WyvernFeature = Union[bool, float, str, List[float], None]`, pydantic would parse `1` or `0` into `true` or `false`. this is wrong.

fix boolean typing

---

poetry.lock
pyproject.toml
wyvern/components/events/events.py
wyvern/config.py
wyvern/exceptions.py
wyvern/experimentation/client.py
wyvern/experimentation/experimentation_logging.py
wyvern/experimentation/providers/base.py
wyvern/experimentation/providers/eppo_provider.py

Support experimentation providers and logging events

---

poetry.lock
pyproject.toml

remove unrelated mypy overrides

---

wyvern/aws/kinesis.py
wyvern/components/features/feature_retrieval_pipeline.py
wyvern/components/features/feature_store.py

remove Joined feature maps log

---

wyvern/event_logging/event_logger.py

fix log_custom_events typing

---

wyvern/wyvern_tracing.py

disable ddtracing in development

---

pyproject.toml

create the beta1 version for 0.0.8

---

wyvern/exceptions.py

add request_id into error message

---

poetry.lock
pyproject.toml

make dependency versions less restrictive

---

pyproject.toml
wyvern/config.py
wyvern/feature_store/historical_feature_util.py

realtime feature log table comes from the environment

---

pyproject.toml
wyvern/feature_store/feature_server.py

get_historical_features - drop unnecessary REQUEST_ID column

---

README.md
docs/development.md
poetry.lock
pyproject.toml

For now, we're deferring all the documentations to https://docs.wyvern.ai

make README easy for now

---

README.md
wyvern/api.py
wyvern/cli/commands.py

decamelize project name for `wyvern init` + docstrings for get_historical_features

---

pyproject.toml
wyvern/components/features/feature_retrieval_pipeline.py
wyvern/components/models/modelbit_component.py
wyvern/components/pipeline_component.py
wyvern/wyvern_request.py

I was getting this error:
```
python3.11/site-packages/wyvern/components/models/modelbit
_component.py", line 105, in inference
if resp.status_code != 200:
^^^^^^^^^^^^^^^^
```
it looks like when we migrate to aiohttp, we forgot to update modelbit model component.

fix modelbit response bug + making feature store value available in realtime feature component

---

sdk_ref.md
wyvern/aws/kinesis.py
wyvern/components/features/feature_store.py
wyvern/config.py

By default, feature store usage and event logging are disabled.

configuration flags for wyvern feature store and event logging

---

wyvern/aws/kinesis.py
wyvern/config.py

default feature store and event logging should be True

---

pyproject.toml
wyvern/components/features/feature_retrieval_pipeline.py
wyvern/components/pipeline_component.py
wyvern/wyvern_request.py

revert feature retrieval dependency

---

wyvern/entities/identifier_entities.py
wyvern/feature_store/feature_server.py

wyvern entity doc update

---

wyvern/components/models/modelbit_component.py

modelbit failure logging fix

---

pyproject.toml
wyvern/cli/commands.py

add current path for wyvern run

---

wyvern/web_frameworks/fastapi.py

fastapi validation error log string fix

---

README.md
pyproject.toml
wyvern/__init__.py
wyvern/cli/commands.py

simplify wyvern import - move top priority import to wyvern/__init__.py

---

README.md

explain the response and update more doc

---

README.md

no need to capitalize Real-time

---

README.md

no need to capitalize machine learning

---

pyproject.toml
wyvern/components/business_logic/business_logic.py
wyvern/components/features/feature_retrieval_pipeline.py
wyvern/components/models/modelbit_component.py
wyvern/components/single_entity_pipeline.py
wyvern/exceptions.py

address feedbacks for single entity pipeline

---

pyproject.toml
wyvern/components/features/feature_retrieval_pipeline.py

Fix how we filter real time features before feature retrieval

---

pyproject.toml
tests/components/business_logic/test_pinning_business_logic.py
tests/scenarios/single_entity_pipelines/test_single_entity_pipeline.py
tests/scenarios/test_product_ranking.py
wyvern/__init__.py
wyvern/components/business_logic/business_logic.py
wyvern/components/component.py
wyvern/components/features/feature_retrieval_pipeline.py
wyvern/components/models/model_chain_component.py
wyvern/components/models/model_component.py
wyvern/components/models/modelbit_component.py
wyvern/components/ranking_pipeline.py
wyvern/components/single_entity_pipeline.py
wyvern/entities/candidate_entities.py
wyvern/entities/model_entities.py
wyvern/exceptions.py
wyvern/service.py
wyvern/web_frameworks/fastapi.py
wyvern/wyvern_request.py

* multi model evaluation
* fix test
* chained model evaluation
* cache model output
* v bump
* support dict model output
* rename
* add get_model_output support
* fix
* 0.0.18-beta1

v0.0.18 - chained model evaluation

---

pyproject.toml
wyvern/components/models/model_component.py

the model_name in model event log should be primary coming from the model.name

---

pyproject.toml
wyvern/components/candidates/candidate_logger.py
wyvern/components/events/events.py
wyvern/components/features/feature_logger.py
wyvern/components/impressions/impression_logger.py
wyvern/components/models/model_component.py
wyvern/event_logging/event_logger.py
wyvern/experimentation/providers/eppo_provider.py
wyvern/web_frameworks/fastapi.py
wyvern/wyvern_request.py

get the run_id from the http header and log run_id by default for every event

---

poetry.lock
pyproject.toml

feast 0.34.1

---

pyproject.toml
wyvern/components/events/events.py

add `event_name` to custom entity event data

---

poetry.lock
pyproject.toml
wyvern/experimentation/providers/base.py
wyvern/experimentation/providers/eppo_provider.py

ykeremy/update eppo sdk to 1.2.3
